artifact_uri: file:///Users/chaitanyakrishnathanneeru/TCK/TCK_Learnings/Practice_Usecases/Financial_MLOps_Project/mlflow_tracking/511650832640770429/7134a60c1bd64fc3ab72fe5ed5886294/artifacts
end_time: 1741855170563
entry_point_name: ''
experiment_id: '511650832640770429'
lifecycle_stage: active
run_id: 7134a60c1bd64fc3ab72fe5ed5886294
run_name: mysterious-lark-663
run_uuid: 7134a60c1bd64fc3ab72fe5ed5886294
source_name: ''
source_type: 4
source_version: ''
start_time: 1741855164410
status: 3
tags: []
user_id: chaitanyakrishnathanneeru
