artifact_uri: file:///Users/chaitanyakrishnathanneeru/TCK/TCK_Learnings/Practice_Usecases/Financial_MLOps_Project/mlflow_tracking/511650832640770429/0dbf0ba88950421bb8dae79eb5d60e3f/artifacts
end_time: 1741854966923
entry_point_name: ''
experiment_id: '511650832640770429'
lifecycle_stage: active
run_id: 0dbf0ba88950421bb8dae79eb5d60e3f
run_name: languid-ox-16
run_uuid: 0dbf0ba88950421bb8dae79eb5d60e3f
source_name: ''
source_type: 4
source_version: ''
start_time: 1741854955958
status: 3
tags: []
user_id: chaitanyakrishnathanneeru
