artifact_uri: file:///Users/chaitanyakrishnathanneeru/TCK/TCK_Learnings/Practice_Usecases/Financial_MLOps_Project/mlflow_tracking/511650832640770429/88d242734f8640a4a2b12372facab252/artifacts
end_time: 1741855210934
entry_point_name: ''
experiment_id: '511650832640770429'
lifecycle_stage: active
run_id: 88d242734f8640a4a2b12372facab252
run_name: beautiful-ox-422
run_uuid: 88d242734f8640a4a2b12372facab252
source_name: ''
source_type: 4
source_version: ''
start_time: 1741855205066
status: 4
tags: []
user_id: chaitanyakrishnathanneeru
