aliases: []
creation_timestamp: 1741854991135
current_stage: None
description: ''
last_updated_timestamp: 1741854991135
name: financial_risk_model
run_id: 0dbf0ba88950421bb8dae79eb5d60e3f
run_link: ''
source: file:///Users/chaitanyakrishnathanneeru/TCK/TCK_Learnings/Practice_Usecases/Financial_MLOps_Project/mlflow_tracking/511650832640770429/0dbf0ba88950421bb8dae79eb5d60e3f/artifacts/models/financial_risk_model
status: READY
status_message: null
storage_location: file:///Users/chaitanyakrishnathanneeru/TCK/TCK_Learnings/Practice_Usecases/Financial_MLOps_Project/mlflow_tracking/511650832640770429/0dbf0ba88950421bb8dae79eb5d60e3f/artifacts/models/financial_risk_model
user_id: null
version: 2
