artifact_uri: file:///Users/chaitanyakrishnathanneeru/TCK/TCK_Learnings/Practice_Usecases/Financial_MLOps_Project/mlflow_tracking/511650832640770429/5cbec7d8394b46cc81002b56178a3736/artifacts
end_time: 1741853749545
entry_point_name: ''
experiment_id: '511650832640770429'
lifecycle_stage: active
run_id: 5cbec7d8394b46cc81002b56178a3736
run_name: enchanting-midge-780
run_uuid: 5cbec7d8394b46cc81002b56178a3736
source_name: ''
source_type: 4
source_version: ''
start_time: 1741853742413
status: 3
tags: []
user_id: chaitanyakrishnathanneeru
